### PR TITLE
Remove `base` and `generic` prefixes from the algorithms files

### PR DESCRIPTION
**Pull request by Janix4000**
I see no purpose for such a prefixes in the file names. New algorithms avoided it and it did not cause any chaos.

Split 'Basin' from 'hopping'. These are two separate words.

### CODE REVIEW

**Comment by Janix4000** [comment]
[Remove base and generic prefixes from the algorithms files](https://trello.com/c/ze3BtP6P/109-remove-base-and-generic-prefixes-from-the-algorithms-files)

**Review by Wolokin — COMMENTED** [review]
edit: moved comment to a change request

**Review by Wolokin — CHANGES_REQUESTED** [review]
> I see no purpose for such a prefixes in the file names. New algorithms avoided it and it did not cause any chaos.
> 
> Split 'Basin' from 'hopping'. These are two separate words.

Why remove prefixes from some files just to add "_impl" suffixes to others? I feel like they add just as little, and I don't see what naming issue it solves to have them. I do however see a person going through these files, seeing an _impl file and then looking for some sort of interface that this _impl implements, just to find out there is none.

**Comment by Janix4000** [comment]
> Why remove prefixes from some files just to add "_impl" suffixes to others? I feel like they add just as little, and I don't see what naming issue it solves to have them. 

Algorithms are classes using Pascal casing, but rules share their function names with their corresponding python files. However, I included function rules into the `votepy.rules` scope, shadowing modules names. There is no way to get other things from these modules. I think it is more natural to import certain function rules from the `votepy.rules`, without additional layer.

> I do however see a person going through these files, seeing an _impl file and then looking for some sort of interface that this _impl implements, just to find out there is none.

Do you prefer different suffix? `_impl` standed for the `_implementation`. What do you think about `_rule` suffix?

**Comment by Wolokin** [comment]
> > Why remove prefixes from some files just to add "_impl" suffixes to others? I feel like they add just as little, and I don't see what naming issue it solves to have them.
> 
> Algorithms are classes using Pascal casing, but rules share their function names with their corresponding python files. However, I included function rules into the `votepy.rules` scope, shadowing modules names. There is no way to get other things from these modules. I think it is more natural to import certain function rules from the `votepy.rules`, without additional layer.

Ok, I admit I didn't notice that overshadowing with the `__init__` file imports, however that stems another issue, since for some rules you can import them as `from votepy.rules import bloc` while different implementations of CC are not visible in the `voting` scope at all, leading to inconsistency - and also we are not using these cleaner imports anywhere, opting for the full `votepy.rules.bloc_impl` name which I just think is too much (and also why I forgot we even had that). I think as a user I wouldn't want to go deeper than votepy.rules, so if we expose all actual voting functions in the `rules` scope, then the actual file names are not as important anymore. 

> > I do however see a person going through these files, seeing an _impl file and then looking for some sort of interface that this _impl implements, just to find out there is none.
> 
> Do you prefer different suffix? `_impl` standed for the `_implementation`. What do you think about `_rule` suffix?

I think that would be better, yes.

**Comment by Janix4000** [comment]
> Ok, I admit I didn't notice that overshadowing with the `__init__` file imports, however that stems another issue, since for some rules you can import them as `from votepy.rules import bloc` while different implementations of CC are not visible in the `voting` scope at all, leading to inconsistency - and also we are not using these cleaner imports anywhere, opting for the full `votepy.rules.bloc_impl` name which I just think is too much (and also why I forgot we even had that). I think as a user I wouldn't want to go deeper than votepy.rules, so if we expose all actual voting functions in the `rules` scope, then the actual file names are not as important anymore. 

Other implementations can be treated as implementation's details and are not part of the public API (maybe they should use `__` prefix?). User have access to their functionality via the main rule function and `algorithm` argument (or `votepy.solve`).

In case of `owa` rules, it makes sense to keep them all under an additional `owa` submodule.

**Comment by Janix4000** [comment]
Changed in #39

**Comment by Wolokin** [comment]
> > Ok, I admit I didn't notice that overshadowing with the `__init__` file imports, however that stems another issue, since for some rules you can import them as `from votepy.rules import bloc` while different implementations of CC are not visible in the `voting` scope at all, leading to inconsistency - and also we are not using these cleaner imports anywhere, opting for the full `votepy.rules.bloc_impl` name which I just think is too much (and also why I forgot we even had that). I think as a user I wouldn't want to go deeper than votepy.rules, so if we expose all actual voting functions in the `rules` scope, then the actual file names are not as important anymore. 
> 
> Other implementations can be treated as implementation's details and are not part of the public API (maybe they should use `__` prefix?). User have access to their functionality via the main rule function and `algorithm` argument (or `votepy.solve`).
> 
> In case of `owa` rules, it makes sense to keep them all under an additional `owa` submodule.

That unfortunately doesn't solve our rule imports which instead of being a one liner are starting to look more like java imports. We can merge this for now, but I would like to revisit at some point.

**Review by Wolokin — APPROVED** [review]

**Review by msluszniak — APPROVED** [review]

**Pull request merged**
